# Kafka Client Configuration Template
# Generated by Terraform MSK module

# Bootstrap servers
bootstrap.servers=${bootstrap_servers}

# Security configuration
security.protocol=${security_protocol}

%{ if security_protocol == "SSL" ~}
# SSL configuration
ssl.truststore.location=${ssl_truststore_location}
ssl.keystore.location=${ssl_keystore_location}
ssl.keystore.password=changeit
ssl.truststore.password=changeit
ssl.key.password=changeit
ssl.endpoint.identification.algorithm=
%{ endif ~}

# Producer configuration
acks=all
retries=2147483647
max.in.flight.requests.per.connection=5
enable.idempotence=true
compression.type=snappy
batch.size=16384
linger.ms=5
buffer.memory=33554432

# Consumer configuration
enable.auto.commit=true
auto.commit.interval.ms=5000
session.timeout.ms=30000
auto.offset.reset=earliest
max.poll.records=500
max.poll.interval.ms=300000

# Connection configuration
connections.max.idle.ms=540000
request.timeout.ms=30000
metadata.max.age.ms=300000
reconnect.backoff.ms=50
reconnect.backoff.max.ms=1000
