---
image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: "latest"

environment:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

persistence:
  enabled: true
  size: 10Gi

resources: {}
