apiVersion: v1
kind: Service
metadata:
  name: {{include "ecap.fullname" .}}
  labels:
    {{- include "ecap.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecap.selectorLabels" . | nindent 4}}
