# Production Environment Configuration
# Configuration overrides for production environment

# Application settings - production optimized
app:
  debug: false
  api:
    workers: 8
    timeout: 30
    cors_origins: ["https://ecap.example.com"]
  dashboard:
    theme: "dark"

# Database configuration - production scale
database:
  pool_size: 20
  max_overflow: 40
  pool_timeout: 60
  pool_recycle: 1800
  echo: false

# Kafka configuration - production cluster
kafka:
  consumer:
    group_id: "ecap-prod-consumer-group"
    batch_size: 2000
    max_poll_records: 1000
    session_timeout_ms: 60000
    heartbeat_interval_ms: 5000

  producer:
    batch_size: 32768
    linger_ms: 5
    buffer_memory: 67108864
    retries: 10
    acks: "all"

# Redis configuration - production
redis:
  max_connections: 50
  db: 0
  socket_timeout: 60
  health_check_interval: 60

# MinIO configuration - production buckets
minio:
  buckets:
    raw_data: "prod-raw-data"
    processed_data: "prod-processed-data"
    analytics_results: "prod-analytics-results"
    model_artifacts: "prod-model-artifacts"
    logs: "prod-logs"
    backups: "prod-backups"

  lifecycle:
    raw_data_retention_days: 365
    processed_data_retention_days: 1095  # 3 years
    logs_retention_days: 90

# Spark configuration - production cluster
spark:
  executor_memory: "4g"
  executor_cores: 4
  driver_memory: "2g"

# Logging configuration - production level
logging:
  level: "WARNING"
  format: "json"
  max_file_size: "500MB"
  backup_count: 10

  loggers:
    uvicorn: "ERROR"
    sqlalchemy: "ERROR"
    kafka: "ERROR"
    ecap: "INFO"

# Monitoring configuration - comprehensive production monitoring
monitoring:
  metrics:
    enabled: true
    interval: 15
    retention_days: 30

  health_checks:
    enabled: true
    interval: 15
    timeout: 5

  alerts:
    enabled: true
    channels: ["email", "slack", "pagerduty"]

# Security configuration - strict production security
security:
  jwt:
    access_token_expire_minutes: 15
    refresh_token_expire_days: 1

  rate_limiting:
    enabled: true
    requests_per_minute: 50
    burst_limit: 100

# Feature flags - stable features only
features:
  fraud_detection: true
  real_time_analytics: true
  customer_segmentation: true
  recommendation_engine: false
  advanced_ml_models: false

# Performance tuning - production optimized
performance:
  connection_pool_size: 20
  max_overflow: 40
  pool_timeout: 60
  query_timeout: 120
  cache_ttl: 300

# Data quality settings - strict production standards
data_quality:
  validation:
    enabled: true
    fail_on_error: true
    max_error_rate: 0.01

# Backup and recovery - comprehensive production backup
backup:
  enabled: true
  interval: "hourly"
  retention_days: 30
  compression: true
  encryption: true
