# Secrets Configuration Template
# This file defines the structure of secrets managed by Vault and Kubernetes

# Application secrets
app:
  secret_key: "${SECRET_KEY}"
  jwt_secret_key: "${JWT_SECRET_KEY}"
  jwt_algorithm: "HS256"
  jwt_access_token_expire_minutes: 30

# Database secrets
database:
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  database: "${DB_NAME}"
  ssl_mode: "prefer"

# Kafka secrets
kafka:
  bootstrap_servers: "${KAFKA_BOOTSTRAP_SERVERS}"
  username: "${KAFKA_USERNAME}"
  password: "${KAFKA_PASSWORD}"
  security_protocol: "SASL_PLAINTEXT"
  sasl_mechanism: "PLAIN"

# Redis secrets
redis:
  host: "${REDIS_HOST}"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"
  db: "${REDIS_DB}"
  ssl: false

# MinIO/S3 secrets
minio:
  endpoint: "${MINIO_ENDPOINT}"
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  secure: "${MINIO_SECURE}"
  region: "${MINIO_REGION}"

# External service secrets
external_services:
  # Monitoring and alerting
  grafana:
    admin_password: "${GRAFANA_ADMIN_PASSWORD}"

  prometheus:
    basic_auth_username: "${PROMETHEUS_USERNAME}"
    basic_auth_password: "${PROMETHEUS_PASSWORD}"

  # Third-party integrations
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    bot_token: "${SLACK_BOT_TOKEN}"

  email:
    smtp_host: "${SMTP_HOST}"
    smtp_port: "${SMTP_PORT}"
    smtp_username: "${SMTP_USERNAME}"
    smtp_password: "${SMTP_PASSWORD}"

# API keys and tokens
api_keys:
  analytics_api_key: "${ANALYTICS_API_KEY}"
  fraud_detection_api_key: "${FRAUD_DETECTION_API_KEY}"
  ml_model_api_key: "${ML_MODEL_API_KEY}"

# Encryption keys
encryption:
  data_encryption_key: "${DATA_ENCRYPTION_KEY}"
  file_encryption_key: "${FILE_ENCRYPTION_KEY}"
  backup_encryption_key: "${BACKUP_ENCRYPTION_KEY}"
