# Staging Environment Configuration Overrides
# Enhanced logging and debugging for staging environment

# Application settings
app:
  debug: true
  environment: "staging"
  api:
    workers: 4
    cors_origins: ["https://staging.ecap.example.com", "http://localhost:3000"]

# Database configuration
database:
  echo: true  # Enable SQL logging for debugging
  pool_size: 10
  max_overflow: 20

# Logging configuration for staging - enhanced debugging
logging:
  level: "DEBUG"
  format: "json"
  output: "both"
  
  # File logging
  file_path: "/app/logs/ecap-staging.log"
  max_file_size: "200MB"
  backup_count: 5
  
  # Enable ELK integration in staging
  elasticsearch:
    enabled: true
    host: "http://elasticsearch:9200"
    index: "ecap-logs-staging"
    buffer_size: 50
    flush_interval: 10.0
  
  # Enhanced request logging for testing
  request_logging:
    enabled: true
    log_request_body: true
    log_response_body: true
    max_body_size: 2048
    slow_request_threshold: 500.0
    very_slow_threshold: 2000.0
  
  # Detailed logger levels for debugging
  loggers:
    uvicorn: "INFO"
    sqlalchemy: "INFO"
    kafka: "INFO"
    elasticsearch: "INFO"
    ecap: "DEBUG"

# Kafka configuration - staging cluster
kafka:
  consumer:
    group_id: "ecap-staging-consumer-group"
    
# MinIO configuration - staging buckets
minio:
  buckets:
    raw_data: "staging-raw-data"
    processed_data: "staging-processed-data"
    analytics_results: "staging-analytics-results"
    model_artifacts: "staging-model-artifacts"
    logs: "staging-logs"
    backups: "staging-backups"

# Performance settings (relaxed for testing)
performance:
  cache_ttl: 60  # Shorter cache for testing
  
# Monitoring (enhanced for staging)
monitoring:
  metrics:
    enabled: true
    interval: 15  # More frequent metrics
    retention_days: 7
  
  health_checks:
    enabled: true
    interval: 15
    timeout: 5
  
  alerts:
    enabled: true
    channels: ["email"]

# Security (relaxed for testing)
security:
  jwt:
    access_token_expire_minutes: 60  # Longer for testing
  
  rate_limiting:
    requests_per_minute: 200  # Higher for load testing

# Features (enable more for testing)
features:
  fraud_detection: true
  real_time_analytics: true
  customer_segmentation: true
  recommendation_engine: true  # Enable in staging
  advanced_ml_models: false

# Data quality (relaxed for testing)
data_quality:
  validation:
    enabled: true
    fail_on_error: false  # Don't fail hard in staging
    max_error_rate: 0.1