apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ecap.fullname" . }}-data
  labels:
    {{- include "ecap.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ecap.fullname" . }}-logs
  labels:
    {{- include "ecap.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logSize }}
