apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "ecap.fullname" .}}
  labels:
    {{- include "ecap.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "ecap.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "ecap.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: spark
              containerPort: 7077
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12}}
